version: '3.7'
services:
    flask:
        environment:
          - TZ=Europe/Moscow
        build: .
        command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
        ports:
            - "5000:5000"
        depends_on:
            - redis
    redis:
        image: redis:5.0.7
        environment:
          - TZ=Europe/Moscow
        ports:
            - "6379:6379"
    celery:
        build: .
        command: celery -A app.application.celery worker --loglevel=INFO
        depends_on:
            - redis
            - flask
